import type { ru } from "./ru";

export const en: Record<keyof typeof ru, string> = {
  today: "Today",
  meetings: "Meetings",
  meetingsHelp:
    "Meeting archive: recordings, minutes, transcripts, and processing status.",
  newMeeting: "New meeting",
  createMeeting: "Create meeting",
  title: "Title",
  startedAt: "Date and time",
  timezone: "Time zone",
  participants: "Participants",
  name: "Name",
  role: "Meeting role",
  add: "Add",
  save: "Save",
  cancel: "Cancel",
  search: "Search",
  searchMeetings: "Search meeting titles…",
  noMeetings: "No meetings yet",
  noMeetingsHelp:
    "Create a meeting to upload a recording and start processing.",
  recordings: "Recordings",
  upload: "Upload audio",
  uploadHelp:
    "Choose WAV, MP3, FLAC, Ogg, WebM, or M4A. The server verifies the format and content.",
  uploading: "Uploading…",
  processing: "Processing",
  startProcessing: "Start processing",
  retryProcessing: "Retry processing",
  noRecording: "No recording uploaded yet.",
  noResult: "No reviewed result is available yet.",
  noResultHelp:
    "The transcript, summary, and action items will appear here after processing. The browser does not invent results.",
  sample: "Synthetic sample — mock server data",
  notice:
    "Inform participants about recording and AI processing. This system does not collect consent confirmations.",
  summary: "Summary",
  overviewTitle: "Meeting overview",
  copyOverview: "Copy overview",
  overviewCopied: "Overview copied",
  overviewCopyFailed: "Could not copy overview",
  overviewDraft: "Draft — needs review",
  overviewConfirmed: "Confirmed minutes",
  overviewEmpty:
    "No summary yet. Generate a draft from the transcript or fill in the result manually.",
  transcript: "Transcript",
  actions: "Action items",
  speakers: "Speakers",
  owner: "Owner",
  deadline: "Deadline",
  status: "Status",
  source: "Source",
  chooseSource: "Link transcript segment",
  unknown: "Not specified",
  unsaved: "Unsaved changes",
  saved: "Saved",
  saveError: "Could not save. Your changes remain in the form.",
  extractDraft: "Generate draft",
  extractingDraft: "Generating draft…",
  extractDisclosure:
    "Transcript text is temporarily sent to an external API. Processing will move to local models later.",
  extractError:
    "Could not generate the draft. Check the API configuration or try again later.",
  extractRefresh: "Refresh result",
  pdf: "Download PDF",
  docx: "Download DOCX",
  exportUnavailable:
    "Export is unavailable until the result is saved on the server.",
  loading: "Loading data…",
  error: "Could not load data.",
  retry: "Retry",
  back: "All meetings",
  details: "Meeting details",
  unavailable:
    "This section is unavailable: the server does not provide these data yet.",
  tasks: "Tasks",
  calendar: "Calendar",
  agenda: "Upcoming",
  analytics: "Task analytics",
  people: "People",
  briefing: "Briefing",
  ask: "Ask the secretary",
  profile: "Profile",
  adminUsers: "Users",
  adminDirectory: "Directory",
  adminAccess: "Category access",
  all: "All",
  open: "Open",
  done: "Done",
  dropped: "Dropped",
  queued: "Queued",
  running: "Running",
  failed: "Failed",
  succeeded: "Completed",
  retryUpload: "Retry this file",
  uploadFailed: "Could not upload the file. It is kept for retry.",
  processingFailed: "Could not process the recording. Please retry.",
  createFailed: "Could not create the meeting. Your form is preserved.",
  invalidDate: "Check the date, time, and time zone.",
  stage_decode: "Preparing audio",
  stage_transcribe: "Transcribing speech",
  stage_diarize: "Identifying speakers",
  stage_extract: "Preparing result",
  stage_complete: "Complete",
  meetingInfo: "Meeting information",
  recordingInfo: "Recording source",
  review: "Review result",
  filterSpeaker: "All speakers",
  noItems: "Nothing found",
  date: "Date",
  actionsCount: "action items",
  meetingCount: "meetings",
  duration: "Duration",
  recordingReady: "Recording ready",
  resultDraft: "Draft result",
  resultSaved: "Reviewed version",
  downloadDraft: "Draft export",
  detailsUnavailable: "The server does not provide these data yet.",
  topics: "Topics",
  decisions: "Decisions",
  openQuestions: "Open questions",
  followAudio: "Follow audio",
  markReviewed: "Result reviewed",
  addAction: "Add action item",
  remove: "Remove",
  receiving: "Receiving file",
  incomplete: "Incomplete recording",
  unavailableStatus: "Unknown status",
  processingSaveFirst:
    "Save your result edits before starting another processing job.",
  fullPipeline: "Transcript, speakers and draft minutes",
  extracting: "Creating draft minutes",
  extractionHelp:
    "The full pipeline runs locally. Creating the draft on CPU currently takes about 15 minutes and may take longer. The result appears after processing finishes and requires manual review and confirmation.",
  processingMode: "Processing mode",
  transcriptionOnly: "Transcript only",
  transcriptionSpeakers: "Transcript and speakers",
  diarizationHelp:
    "The system will separate voices in the recording. After processing, listen to the samples and identify participants manually.",
  diarizing: "Identifying speakers",
  diarizationUnavailable:
    "The voice separation model is not available yet. You can choose “Transcript only”.",
  speakerHelp:
    "Choose a person for a detected voice: their name immediately appears on the timeline and every turn by that voice. Click Save above to keep the change. Action item owners are assigned separately.",
  voiceSegments: "turns",
  showVoiceRows: "Show turns",
  voiceAssignmentPending: "Unsaved — click Save above",
  speakerSample: "Go to sample",
  listenSpeaker: "Listen",
  stopSolo: "All voices",
  speakerMerged: "Merged into",
  noSpeakers: "No distinct voices were found in this recording.",
  speakersUnavailable: "Run “Transcript and speakers” to identify voices.",
  reviewConflict:
    "Another session saved a newer revision. Your edits remain in the form.",
  reviewReload: "Load server revision",
  reviewReloadHelp:
    "This replaces unsaved fields. Keep a separate copy of any edits you need before loading.",
  reviewReloadError:
    "Could not load the revision. Your edits remain in the form.",
};
