import type { ru } from "./ru";

export const en: Record<keyof typeof ru, string> = {
  today: "Today",
  meetings: "Meetings",
  meetingsHelp:
    "Meeting archive: recordings, minutes, transcripts, and processing status.",
  newMeeting: "New meeting",
  createMeeting: "Create meeting",
  title: "Title",
  startedAt: "Date and time",
  timezone: "Time zone",
  participants: "Participants",
  name: "Name",
  role: "Meeting role",
  add: "Add",
  save: "Save",
  cancel: "Cancel",
  search: "Search",
  searchMeetings: "Search meeting titles…",
  noMeetings: "No meetings yet",
  noMeetingsHelp:
    "Create a meeting to upload a recording and start processing.",
  recordings: "Recordings",
  upload: "Upload audio",
  uploadHelp:
    "Choose WAV, MP3, FLAC, Ogg, WebM, or M4A. The server verifies the format and content.",
  uploading: "Uploading…",
  processing: "Processing",
  startProcessing: "Start processing",
  retryProcessing: "Retry processing",
  noRecording: "No recording uploaded yet.",
  noResult: "No reviewed result is available yet.",
  noResultHelp:
    "The transcript, summary, and action items will appear here after processing. The browser does not invent results.",
  sample: "Synthetic sample — mock server data",
  notice:
    "Inform participants about recording and AI processing. This system does not collect consent confirmations.",
  summary: "Summary",
  transcript: "Transcript",
  actions: "Action items",
  speakers: "Speakers",
  owner: "Owner",
  deadline: "Deadline",
  status: "Status",
  source: "Source",
  unknown: "Not specified",
  unsaved: "Unsaved changes",
  saved: "Saved",
  saveError: "Could not save. Your changes remain in the form.",
  pdf: "Download PDF",
  docx: "Download DOCX",
  exportUnavailable:
    "Export is unavailable until the result is saved on the server.",
  loading: "Loading data…",
  error: "Could not load data.",
  retry: "Retry",
  back: "All meetings",
  details: "Meeting details",
  unavailable:
    "This section is unavailable: the server does not provide these data yet.",
  tasks: "Tasks",
  calendar: "Calendar",
  agenda: "Upcoming",
  analytics: "Task analytics",
  people: "People",
  briefing: "Briefing",
  ask: "Ask the secretary",
  profile: "Profile",
  adminUsers: "Users",
  adminDirectory: "Directory",
  adminAccess: "Category access",
  all: "All",
  open: "Open",
  done: "Done",
  dropped: "Dropped",
  queued: "Queued",
  running: "Running",
  failed: "Failed",
  succeeded: "Completed",
  retryUpload: "Choose the file again",
  meetingInfo: "Meeting information",
  recordingInfo: "Recording source",
  review: "Review result",
  filterSpeaker: "All speakers",
  noItems: "Nothing found",
  date: "Date",
  actionsCount: "action items",
  meetingCount: "meetings",
  duration: "Duration",
  recordingReady: "Recording ready",
  resultDraft: "Draft result",
  resultSaved: "Reviewed version",
  downloadDraft: "Draft export",
  detailsUnavailable: "The server does not provide these data yet.",
  topics: "Topics",
  decisions: "Decisions",
  openQuestions: "Open questions",
  followAudio: "Follow audio",
  markReviewed: "Result reviewed",
  addAction: "Add action item",
  remove: "Remove",
  receiving: "Receiving file",
  incomplete: "Incomplete recording",
  unavailableStatus: "Unknown status",
  reviewConflict: "Another session saved a newer revision. Your edits remain in the form.",
  reviewReload: "Load server revision",
  reviewReloadHelp: "This replaces unsaved fields. Keep a separate copy of any edits you need before loading.",
  reviewReloadError: "Could not load the revision. Your edits remain in the form.",
};
