import type { ru } from "./ru";

export const kk: Record<keyof typeof ru, string> = {
  today: "Бүгін",
  meetings: "Кездесулер",
  meetingsHelp:
    "Кездесулер мұрағаты: жазбалар, хаттамалар, транскрипттер және өңдеу күйі.",
  newMeeting: "Жаңа кездесу",
  createMeeting: "Кездесу құру",
  title: "Атауы",
  startedAt: "Күні мен уақыты",
  timezone: "Уақыт белдеуі",
  participants: "Қатысушылар",
  name: "Аты",
  role: "Кездесудегі рөлі",
  add: "Қосу",
  save: "Сақтау",
  cancel: "Бас тарту",
  search: "Іздеу",
  searchMeetings: "Кездесу атауы бойынша іздеу…",
  noMeetings: "Әзірге кездесу жоқ",
  noMeetingsHelp: "Жазбаны жүктеп, өңдеуді бастау үшін кездесу құрыңыз.",
  recordings: "Жазбалар",
  upload: "Аудио жүктеу",
  uploadHelp:
    "WAV, MP3, FLAC, Ogg, WebM немесе M4A таңдаңыз. Пішім мен мазмұнды сервер тексереді.",
  uploading: "Жүктелуде…",
  processing: "Өңдеу",
  startProcessing: "Өңдеуді бастау",
  retryProcessing: "Өңдеуді қайталау",
  noRecording: "Жазба әлі жүктелмеген.",
  noResult: "Тексерілген нәтиже әзірге жоқ.",
  noResultHelp:
    "Өңдеуден кейін транскрипт, түйіндеме және тапсырмалар осында шығады. Браузер қорытынды жасамайды.",
  sample: "Синтетикалық үлгі — mock-сервер деректері",
  notice:
    "Қатысушыларға жазба және ЖИ өңдеуі туралы хабарлаңыз. Бұл жүйе келісімді растамайды.",
  summary: "Түйіндеме",
  transcript: "Транскрипт",
  actions: "Тапсырмалар",
  speakers: "Сөйлеушілер",
  owner: "Жауапты",
  deadline: "Мерзім",
  status: "Күйі",
  source: "Дереккөз",
  chooseSource: "Сөйлеу бөлігін байланыстыру",
  unknown: "Көрсетілмеген",
  unsaved: "Сақталмаған түзетулер бар",
  saved: "Сақталды",
  saveError: "Сақтау мүмкін болмады. Түзетулер пішінде қалды.",
  pdf: "PDF жүктеу",
  docx: "DOCX жүктеу",
  exportUnavailable: "Нәтиже серверде сақталғанша экспорт қолжетімсіз.",
  loading: "Деректер жүктелуде…",
  error: "Деректерді жүктеу мүмкін болмады.",
  retry: "Қайталау",
  back: "Барлық кездесулер",
  details: "Кездесу мәліметтері",
  unavailable: "Бұл бөлім әзірге қолжетімсіз: сервер бұл деректерді ұсынбайды.",
  tasks: "Тапсырмалар",
  calendar: "Күнтізбе",
  agenda: "Алдағы",
  analytics: "Тапсырмалар талдауы",
  people: "Адамдар",
  briefing: "Брифинг",
  ask: "Хатшыдан сұрау",
  profile: "Профиль",
  adminUsers: "Пайдаланушылар",
  adminDirectory: "Ұйым анықтамалығы",
  adminAccess: "Санаттарға қолжетімділік",
  all: "Барлығы",
  open: "Жұмыста",
  done: "Орындалды",
  dropped: "Алып тасталды",
  queued: "Кезекте",
  running: "Орындалуда",
  failed: "Қате",
  succeeded: "Аяқталды",
  retryUpload: "Осы файлмен қайталау",
  uploadFailed: "Файл жүктелмеді. Қайта көру үшін файл сақталды.",
  processingFailed: "Жазбаны өңдеу мүмкін болмады. Қайталап көріңіз.",
  createFailed: "Кездесу құрылмады. Пішін деректері сақталды.",
  invalidDate: "Күнді, уақытты және уақыт белдеуін тексеріңіз.",
  stage_decode: "Аудионы дайындау",
  stage_transcribe: "Сөйлеуді тану",
  stage_diarize: "Сөйлеушілерді анықтау",
  stage_extract: "Нәтижені дайындау",
  stage_complete: "Дайын",
  meetingInfo: "Кездесу параметрлері",
  recordingInfo: "Жазба көзі",
  review: "Нәтижені тексеру",
  filterSpeaker: "Барлық сөйлеушілер",
  noItems: "Ештеңе табылмады",
  date: "Күні",
  actionsCount: "тапсырма",
  meetingCount: "кездесу",
  duration: "Ұзақтығы",
  recordingReady: "Жазба дайын",
  resultDraft: "Нәтиже жобасы",
  resultSaved: "Тексерілген нұсқа",
  downloadDraft: "Жоба экспорты",
  detailsUnavailable: "Сервер бұл деректерді әлі ұсынбайды.",
  topics: "Тақырыптар",
  decisions: "Шешімдер",
  openQuestions: "Ашық сұрақтар",
  followAudio: "Аудионы қадағалау",
  markReviewed: "Нәтиже тексерілді",
  addAction: "Тапсырма қосу",
  remove: "Жою",
  receiving: "Файл қабылдануда",
  incomplete: "Толық емес жазба",
  unavailableStatus: "Белгісіз күй",
  reviewConflict:
    "Басқа сеанста жаңа түзету нұсқасы сақталды. Өзгерістеріңіз пішінде қалды.",
  reviewReload: "Сервердегі нұсқаны жүктеу",
  reviewReloadHelp:
    "Бұл сақталмаған өрістерді ауыстырады. Жүктемес бұрын қажетті өзгерістерді бөлек сақтаңыз.",
  reviewReloadError:
    "Нұсқаны жүктеу мүмкін болмады. Өзгерістеріңіз пішінде қалды.",
};
