export const ru = {
  today: "Сегодня",
  meetings: "Встречи",
  meetingsHelp:
    "Архив совещаний: записи, протоколы, транскрипты и статус обработки.",
  newMeeting: "Новая встреча",
  createMeeting: "Создать встречу",
  title: "Название",
  startedAt: "Дата и время",
  timezone: "Часовой пояс",
  participants: "Участники",
  name: "Имя",
  role: "Роль на встрече",
  add: "Добавить",
  save: "Сохранить",
  cancel: "Отмена",
  search: "Поиск",
  searchMeetings: "Поиск по названию встречи…",
  noMeetings: "Встреч пока нет",
  noMeetingsHelp:
    "Создайте встречу, чтобы загрузить запись и запустить обработку.",
  recordings: "Записи",
  upload: "Загрузить аудио",
  uploadHelp:
    "Выберите WAV, MP3, FLAC, Ogg, WebM или M4A. Формат и содержимое проверяет сервер.",
  uploading: "Загрузка…",
  processing: "Обработка",
  startProcessing: "Начать обработку",
  retryProcessing: "Повторить обработку",
  noRecording: "Запись ещё не загружена.",
  noResult: "Проверенный результат пока недоступен.",
  noResultHelp:
    "После обработки здесь появятся транскрипт, саммари и поручения. Никакие выводы не создаются в браузере.",
  sample: "Синтетический пример — данные mock-сервера",
  notice:
    "Сообщите участникам о записи и ИИ-обработке. Подтверждение согласия в этой системе не собирается.",
  summary: "Саммари",
  transcript: "Транскрипт",
  actions: "Поручения",
  speakers: "Говорящие",
  owner: "Ответственный",
  deadline: "Срок",
  status: "Статус",
  source: "Источник",
  unknown: "Не указан",
  unsaved: "Есть несохранённые правки",
  saved: "Сохранено",
  saveError: "Не удалось сохранить. Ваши правки остались в форме.",
  pdf: "Скачать PDF",
  docx: "Скачать DOCX",
  exportUnavailable: "Экспорт недоступен до сохранения результата на сервере.",
  loading: "Загрузка данных…",
  error: "Не удалось загрузить данные.",
  retry: "Повторить",
  back: "Все встречи",
  details: "Детали встречи",
  unavailable:
    "Раздел пока недоступен: сервер ещё не предоставляет эти данные.",
  tasks: "Задачи",
  calendar: "Календарь",
  agenda: "Предстоящее",
  analytics: "Аналитика задач",
  people: "Люди",
  briefing: "Брифинг",
  ask: "Спросить секретаря",
  profile: "Профиль",
  adminUsers: "Пользователи",
  adminDirectory: "Оргсправочник",
  adminAccess: "Доступ по категориям",
  all: "Все",
  open: "В работе",
  done: "Выполнено",
  dropped: "Снято",
  queued: "В очереди",
  running: "Выполняется",
  failed: "Ошибка",
  succeeded: "Завершено",
  retryUpload: "Выберите файл ещё раз",
  meetingInfo: "Параметры встречи",
  recordingInfo: "Источник записи",
  review: "Проверка результата",
  filterSpeaker: "Все говорящие",
  noItems: "Ничего не найдено",
  date: "Дата",
  actionsCount: "поручений",
  meetingCount: "встреч",
  duration: "Длительность",
  recordingReady: "Запись готова",
  resultDraft: "Черновик результата",
  resultSaved: "Проверенная версия",
  downloadDraft: "Черновой экспорт",
  detailsUnavailable: "Эти данные ещё не предоставляются сервером.",
  topics: "Темы",
  decisions: "Решения",
  openQuestions: "Открытые вопросы",
  followAudio: "Следить за аудио",
  markReviewed: "Результат проверен",
  addAction: "Добавить поручение",
  remove: "Удалить",
  receiving: "Приём файла",
  incomplete: "Неполная запись",
  unavailableStatus: "Неизвестный статус",
  reviewConflict: "В другом сеансе сохранена новая ревизия. Ваши правки остались в форме.",
  reviewReload: "Загрузить серверную ревизию",
  reviewReloadHelp: "Это заменит несохранённые поля. Перед загрузкой сохраните нужные правки отдельно.",
  reviewReloadError: "Не удалось загрузить ревизию. Ваши правки остались в форме.",
} as const;
